### ISSUE TITLE
Organisation secretes cannot be used in PR

### ISSUE THREAD

**Issue by dhschall** [vhive-serverless/vSwarm#360]
**Describe the bug**
It seems that within a PR the organisation's secrets cannot be used anymore.
I.e., see https://github.com/vhive-serverless/vSwarm/actions/runs/3477182317/jobs/5894435705
or https://github.com/vhive-serverless/vSwarm/actions/runs/3512331803/jobs/5883934394

I assume this might be happening due to a change from Github. Maybe they do allow not any more access to organization secretes in PRs.

**Comment by alannair** [comment]
The two jobs are failing due to two different reasons.

Regarding the first one, according to [github docs](https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow)
> With the exception of `GITHUB_TOKEN`, secrets are not passed to the runner when a workflow is triggered from a forked repository.

This was always the case (and not due to any recent change from Github), and this was why I had to move my _multi-cloud support_ work from a forked repository to a branch on this repository (see PR [#297](https://github.com/vhive-serverless/vSwarm/pull/297)).
I am not aware of any other workaround, unfortunately.

Regarding the second failed job, I think that is indeed due to a change from Github. Dependabot-triggered PRs can no longer access organization secrets. See [this comment](https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544) and [github docs](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#accessing-secrets).
Lets discuss how we want to tackle this problem.

**Comment by dhschall** [comment]
Thank you @alannair. Ill try to find a way how to handle that.
Its annoying as now no more testing is possible before merging a dependabot PR

**Comment by dhschall** [comment]
Ok I added organisation secrets for the depandabot in the settings.
For the one workloads I retriggerd it works now
https://github.com/vhive-serverless/vSwarm/actions/runs/3512331803/jobs/5912864639
I suppose we do not need the PR anymore.
Lets wait until the dependabot update gets rescheduled. I think this should be Monday.

**Comment by dhschall** [comment]
Ok so this seems now fixed:
https://github.com/vhive-serverless/vSwarm/actions/runs/3643808094/jobs/6152387982

**Comment by alannair** [comment]
@dhschall So this issue can be closed, yes?

**Comment by dhschall** [comment]
Can you maybe just approve this one #361
Then it should close this issue automatically
